runtime: node010

build: |
  {{ parent }}
  rm -f npm-shrinkwrap.json

publish: exec npm publish

test: |
  {{ parent }}

  if [[ "$ROCK_ARGS_ALL" == "true" ]]; then
    mocha test/integration.js
  fi
