runtime: node010

build: |
  {{ parent }}
  rm -f npm-shrinkwrap.json

publish: npm publish

test: |
  mocha
  jshint jenkins.js

unit: |
  mocha test/unit.js
  jshint jenkins.js

integration: mocha test/integration.js
