runtime: node010

build: |
  {{ parent }}
  rm -f npm-shrinkwrap.json

build_publish: npm publish

test: |
  mocha
  jshint jenkins.js

test_unit: mocha test/unit.js
test_integration: mocha test/integration.js
